#!/usr/bin/env python3
"""Merge checks/query/*.yaml into one clang-tidy config.

Each file under checks/query/ holds one CustomChecks entry (Name, Query,
Diagnostic). clang-tidy wants them as a single list in one config, so this
writes dist/tidy-agent.clang-tidy, which readers either copy into their own
.clang-tidy or pass with --config-file.

Usage: tools/build_config.py [--only NAME ...] [--out PATH]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
QUERY_DIR = ROOT / "checks" / "query"
DEFAULT_OUT = ROOT / "dist" / "tidy-agent.clang-tidy"


def load_entries(only: list[str] | None) -> list[dict]:
    entries = []
    for path in sorted(QUERY_DIR.glob("*.yaml")):
        entry = yaml.safe_load(path.read_text())
        short = entry["Name"].removeprefix("wrocpp-")
        if only and short not in only and entry["Name"] not in only:
            continue
        entries.append(entry)
    if only and not entries:
        sys.exit(f"error: no query check matches {only}")
    return entries


def render(entries: list[dict]) -> str:
    checks = ",".join(f"custom-{e['Name']}" for e in entries)
    config = {"Checks": f"-*,{checks}", "CustomChecks": entries}
    header = "# Generated by tools/build_config.py from checks/query/. Do not edit.\n"
    return header + yaml.safe_dump(config, sort_keys=False, width=100)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--only", nargs="*", help="check names to include (default: all)")
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(load_entries(args.only)))
    print(args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
